name: Build
on:
  push: 
    branches: 
      - master
  pull_request:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker build -t juice-shop:${{github.sha}} .

      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: juice-shop:${{github.sha}}

      - name: Generate Sbom
        uses: anchore/sbom-action@v0
        with:
          image: juice-shop:${{github.sha}}
          
  Sast-scan:
    name: sast
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: semgrep scan
        run: semgrep ci --config=auto --sarif -o result.sarif || true

      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: result.sarif
          path: result.sarif
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://www.zaproxy.org'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


          
