name: Build
on:
  push: 
    branches: 
      - master
  pull_request:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker build -t juice-shop:${{github.sha}} .

  
